/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'funny' : IDL.Null,
  'other' : IDL.Null,
  'love' : IDL.Null,
  'random' : IDL.Null,
  'confession' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Story = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'category' : Category,
  'image' : IDL.Opt(ExternalBlob),
  'location' : Location,
  'pinCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'seenIntro' : IDL.Bool,
  'pinnedStories' : IDL.Vec(IDL.Text),
  'username' : IDL.Text,
  'storiesPosted' : IDL.Nat,
  'likedStories' : IDL.Vec(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'storyId' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'storyId' : IDL.Text,
  'timestamp' : IDL.Int,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
});
export const SearchParams = IDL.Record({
  'keywords' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'radius' : IDL.Opt(IDL.Float64),
  'coordinates' : Location,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStory' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        Location,
        IDL.Int,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getRecentStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getStoriesByCategory' : IDL.Func([Category], [IDL.Vec(Story)], ['query']),
  'getStoryById' : IDL.Func([IDL.Text], [Story], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSeenIntro' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeStory' : IDL.Func([IDL.Text], [], []),
  'markIntroSeen' : IDL.Func([], [], []),
  'pinStory' : IDL.Func([IDL.Text], [], []),
  'removeReport' : IDL.Func([IDL.Nat], [], []),
  'removeStory' : IDL.Func([IDL.Text], [], []),
  'reportStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStories' : IDL.Func([SearchParams], [IDL.Vec(Story)], ['query']),
  'unlikeStory' : IDL.Func([IDL.Text], [], []),
  'unpinStory' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'funny' : IDL.Null,
    'other' : IDL.Null,
    'love' : IDL.Null,
    'random' : IDL.Null,
    'confession' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Story = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'category' : Category,
    'image' : IDL.Opt(ExternalBlob),
    'location' : Location,
    'pinCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'seenIntro' : IDL.Bool,
    'pinnedStories' : IDL.Vec(IDL.Text),
    'username' : IDL.Text,
    'storiesPosted' : IDL.Nat,
    'likedStories' : IDL.Vec(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'storyId' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'storyId' : IDL.Text,
    'timestamp' : IDL.Int,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const SearchParams = IDL.Record({
    'keywords' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'radius' : IDL.Opt(IDL.Float64),
    'coordinates' : Location,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStory' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          Location,
          IDL.Int,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getRecentStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getStoriesByCategory' : IDL.Func([Category], [IDL.Vec(Story)], ['query']),
    'getStoryById' : IDL.Func([IDL.Text], [Story], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSeenIntro' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeStory' : IDL.Func([IDL.Text], [], []),
    'markIntroSeen' : IDL.Func([], [], []),
    'pinStory' : IDL.Func([IDL.Text], [], []),
    'removeReport' : IDL.Func([IDL.Nat], [], []),
    'removeStory' : IDL.Func([IDL.Text], [], []),
    'reportStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStories' : IDL.Func([SearchParams], [IDL.Vec(Story)], ['query']),
    'unlikeStory' : IDL.Func([IDL.Text], [], []),
    'unpinStory' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };