/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LocalCategory = IDL.Variant({
  'nature' : IDL.Null,
  'event' : IDL.Null,
  'traffic' : IDL.Null,
  'general' : IDL.Null,
  'power' : IDL.Null,
  'police' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'funny' : IDL.Null,
  'other' : IDL.Null,
  'love' : IDL.Null,
  'random' : IDL.Null,
  'confession' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const LocalUpdatePublic = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'longitude' : IDL.Float64,
  'thumbsUp' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : LocalCategory,
  'radius' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
});
export const Story = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Principal,
  'viewCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : Category,
  'image' : IDL.Opt(ExternalBlob),
  'location' : Location,
  'pinCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'seenIntro' : IDL.Bool,
  'pinnedStories' : IDL.Vec(IDL.Text),
  'username' : IDL.Text,
  'storiesPosted' : IDL.Nat,
  'likedStories' : IDL.Vec(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'storyId' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const StoryDraft = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'timestamp' : IDL.Int,
  'category' : Category,
  'image' : IDL.Opt(ExternalBlob),
  'location' : IDL.Opt(Location),
});
export const StoryView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'author' : IDL.Principal,
  'viewCount' : IDL.Nat,
  'viewers' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Int,
  'category' : Category,
  'image' : IDL.Opt(ExternalBlob),
  'location' : Location,
  'pinCount' : IDL.Nat,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'storyId' : IDL.Text,
  'timestamp' : IDL.Int,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
});
export const SortOption = IDL.Variant({
  'nearest' : IDL.Record({ 'location' : Location }),
  'newest' : IDL.Null,
  'mostPinned' : IDL.Null,
  'mostLiked' : IDL.Null,
  'mostViewed' : IDL.Null,
});
export const ProximityQuery = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const SearchParams = IDL.Record({
  'sort' : SortOption,
  'keywords' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'radius' : IDL.Opt(IDL.Float64),
  'coordinates' : Location,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addLocalUpdate' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        LocalCategory,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDraft' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Opt(Location),
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'createStory' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        Location,
        IDL.Int,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'deleteDraft' : IDL.Func([IDL.Text], [], []),
  'getActiveLocalUpdatesByProximity' : IDL.Func(
      [Location],
      [IDL.Vec(LocalUpdatePublic)],
      ['query'],
    ),
  'getAllActiveLocalUpdates' : IDL.Func(
      [],
      [IDL.Vec(LocalUpdatePublic)],
      ['query'],
    ),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getDraft' : IDL.Func([IDL.Text], [IDL.Opt(StoryDraft)], ['query']),
  'getLikedStoriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StoryView)],
      ['query'],
    ),
  'getLocalUpdateById' : IDL.Func([IDL.Nat], [LocalUpdatePublic], ['query']),
  'getLocalUpdatesByCategory' : IDL.Func(
      [LocalCategory],
      [IDL.Vec(LocalUpdatePublic)],
      ['query'],
    ),
  'getPinnedStoriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StoryView)],
      ['query'],
    ),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getStoriesByCategory' : IDL.Func(
      [Category, SortOption],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getStoriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StoryView)],
      ['query'],
    ),
  'getStoryById' : IDL.Func([IDL.Text], [Story], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSeenIntro' : IDL.Func([], [IDL.Bool], ['query']),
  'incrementStoryViewCount' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeStory' : IDL.Func([IDL.Text], [], []),
  'listDrafts' : IDL.Func([], [IDL.Vec(StoryDraft)], ['query']),
  'markIntroSeen' : IDL.Func([], [], []),
  'pinStory' : IDL.Func([IDL.Text], [], []),
  'publishDraft' : IDL.Func([IDL.Text], [IDL.Text], []),
  'queryByProximity' : IDL.Func(
      [ProximityQuery],
      [IDL.Vec(LocalUpdatePublic)],
      ['query'],
    ),
  'removeLocalUpdate' : IDL.Func([IDL.Nat], [], []),
  'removeReport' : IDL.Func([IDL.Nat], [], []),
  'removeStory' : IDL.Func([IDL.Text], [], []),
  'reportStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStories' : IDL.Func([SearchParams], [IDL.Vec(Story)], ['query']),
  'thumbsUpLocalUpdate' : IDL.Func([IDL.Nat], [], []),
  'unlikeStory' : IDL.Func([IDL.Text], [], []),
  'unpinStory' : IDL.Func([IDL.Text], [], []),
  'updateDraft' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Opt(Location),
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateStory' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Category,
        Location,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LocalCategory = IDL.Variant({
    'nature' : IDL.Null,
    'event' : IDL.Null,
    'traffic' : IDL.Null,
    'general' : IDL.Null,
    'power' : IDL.Null,
    'police' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'funny' : IDL.Null,
    'other' : IDL.Null,
    'love' : IDL.Null,
    'random' : IDL.Null,
    'confession' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const LocalUpdatePublic = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'longitude' : IDL.Float64,
    'thumbsUp' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : LocalCategory,
    'radius' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Story = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Principal,
    'viewCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : Category,
    'image' : IDL.Opt(ExternalBlob),
    'location' : Location,
    'pinCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'seenIntro' : IDL.Bool,
    'pinnedStories' : IDL.Vec(IDL.Text),
    'username' : IDL.Text,
    'storiesPosted' : IDL.Nat,
    'likedStories' : IDL.Vec(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'storyId' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const StoryDraft = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'timestamp' : IDL.Int,
    'category' : Category,
    'image' : IDL.Opt(ExternalBlob),
    'location' : IDL.Opt(Location),
  });
  const StoryView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'author' : IDL.Principal,
    'viewCount' : IDL.Nat,
    'viewers' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Int,
    'category' : Category,
    'image' : IDL.Opt(ExternalBlob),
    'location' : Location,
    'pinCount' : IDL.Nat,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'storyId' : IDL.Text,
    'timestamp' : IDL.Int,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const SortOption = IDL.Variant({
    'nearest' : IDL.Record({ 'location' : Location }),
    'newest' : IDL.Null,
    'mostPinned' : IDL.Null,
    'mostLiked' : IDL.Null,
    'mostViewed' : IDL.Null,
  });
  const ProximityQuery = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const SearchParams = IDL.Record({
    'sort' : SortOption,
    'keywords' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'radius' : IDL.Opt(IDL.Float64),
    'coordinates' : Location,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addLocalUpdate' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          LocalCategory,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDraft' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Opt(Location),
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'createStory' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          Location,
          IDL.Int,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'deleteDraft' : IDL.Func([IDL.Text], [], []),
    'getActiveLocalUpdatesByProximity' : IDL.Func(
        [Location],
        [IDL.Vec(LocalUpdatePublic)],
        ['query'],
      ),
    'getAllActiveLocalUpdates' : IDL.Func(
        [],
        [IDL.Vec(LocalUpdatePublic)],
        ['query'],
      ),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getDraft' : IDL.Func([IDL.Text], [IDL.Opt(StoryDraft)], ['query']),
    'getLikedStoriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StoryView)],
        ['query'],
      ),
    'getLocalUpdateById' : IDL.Func([IDL.Nat], [LocalUpdatePublic], ['query']),
    'getLocalUpdatesByCategory' : IDL.Func(
        [LocalCategory],
        [IDL.Vec(LocalUpdatePublic)],
        ['query'],
      ),
    'getPinnedStoriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StoryView)],
        ['query'],
      ),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getStoriesByCategory' : IDL.Func(
        [Category, SortOption],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getStoriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StoryView)],
        ['query'],
      ),
    'getStoryById' : IDL.Func([IDL.Text], [Story], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSeenIntro' : IDL.Func([], [IDL.Bool], ['query']),
    'incrementStoryViewCount' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeStory' : IDL.Func([IDL.Text], [], []),
    'listDrafts' : IDL.Func([], [IDL.Vec(StoryDraft)], ['query']),
    'markIntroSeen' : IDL.Func([], [], []),
    'pinStory' : IDL.Func([IDL.Text], [], []),
    'publishDraft' : IDL.Func([IDL.Text], [IDL.Text], []),
    'queryByProximity' : IDL.Func(
        [ProximityQuery],
        [IDL.Vec(LocalUpdatePublic)],
        ['query'],
      ),
    'removeLocalUpdate' : IDL.Func([IDL.Nat], [], []),
    'removeReport' : IDL.Func([IDL.Nat], [], []),
    'removeStory' : IDL.Func([IDL.Text], [], []),
    'reportStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStories' : IDL.Func([SearchParams], [IDL.Vec(Story)], ['query']),
    'thumbsUpLocalUpdate' : IDL.Func([IDL.Nat], [], []),
    'unlikeStory' : IDL.Func([IDL.Text], [], []),
    'unpinStory' : IDL.Func([IDL.Text], [], []),
    'updateDraft' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Opt(Location),
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateStory' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Category,
          Location,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };