/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'funny' : null } |
  { 'other' : null } |
  { 'love' : null } |
  { 'random' : null } |
  { 'confession' : null };
export interface Comment {
  'id' : bigint,
  'content' : string,
  'storyId' : string,
  'isAnonymous' : boolean,
  'author' : Principal,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Location { 'latitude' : number, 'longitude' : number }
export interface Report {
  'id' : bigint,
  'storyId' : string,
  'timestamp' : bigint,
  'reporter' : Principal,
  'reason' : string,
}
export interface SearchParams {
  'keywords' : [] | [string],
  'category' : [] | [Category],
  'radius' : [] | [number],
  'coordinates' : Location,
}
export interface Story {
  'id' : string,
  'title' : string,
  'likeCount' : bigint,
  'content' : string,
  'isAnonymous' : boolean,
  'author' : Principal,
  'timestamp' : bigint,
  'category' : Category,
  'image' : [] | [ExternalBlob],
  'location' : Location,
  'pinCount' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'seenIntro' : boolean,
  'pinnedStories' : Array<string>,
  'username' : string,
  'storiesPosted' : bigint,
  'likedStories' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string, bigint, boolean], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStory' : ActorMethod<
    [string, string, Category, Location, bigint, boolean, [] | [ExternalBlob]],
    string
  >,
  'getAllStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getRecentStories' : ActorMethod<[bigint], Array<Story>>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getStoriesByCategory' : ActorMethod<[Category], Array<Story>>,
  'getStoryById' : ActorMethod<[string], Story>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasSeenIntro' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeStory' : ActorMethod<[string], undefined>,
  'markIntroSeen' : ActorMethod<[], undefined>,
  'pinStory' : ActorMethod<[string], undefined>,
  'removeReport' : ActorMethod<[bigint], undefined>,
  'removeStory' : ActorMethod<[string], undefined>,
  'reportStory' : ActorMethod<[string, string, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStories' : ActorMethod<[SearchParams], Array<Story>>,
  'unlikeStory' : ActorMethod<[string], undefined>,
  'unpinStory' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];