/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface Comment {
    id: bigint;
    content: string;
    storyId: string;
    isAnonymous: boolean;
    author: Principal;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Story {
    id: string;
    title: string;
    likeCount: bigint;
    content: string;
    isAnonymous: boolean;
    author: Principal;
    viewCount: bigint;
    timestamp: bigint;
    category: Category;
    image?: ExternalBlob;
    location: Location;
    pinCount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: bigint;
    storyId: string;
    timestamp: bigint;
    reporter: Principal;
    reason: string;
}
export interface SearchParams {
    sort: SortOption;
    keywords?: string;
    category?: Category;
    radius?: number;
    coordinates: Location;
}
export interface StoryDraft {
    id: string;
    title: string;
    content: string;
    createdAt: bigint;
    isAnonymous: boolean;
    author: Principal;
    updatedAt: bigint;
    timestamp: bigint;
    category: Category;
    image?: ExternalBlob;
    location?: Location;
}
export interface StoryView {
    id: string;
    title: string;
    likeCount: bigint;
    content: string;
    isAnonymous: boolean;
    author: Principal;
    viewCount: bigint;
    viewers: Array<Principal>;
    timestamp: bigint;
    category: Category;
    image?: ExternalBlob;
    location: Location;
    pinCount: bigint;
}
export type SortOption = {
    __kind__: "nearest";
    nearest: {
        location: Location;
    };
} | {
    __kind__: "newest";
    newest: null;
} | {
    __kind__: "mostPinned";
    mostPinned: null;
} | {
    __kind__: "mostLiked";
    mostLiked: null;
} | {
    __kind__: "mostViewed";
    mostViewed: null;
};
export interface UserProfile {
    id: Principal;
    seenIntro: boolean;
    pinnedStories: Array<string>;
    username: string;
    storiesPosted: bigint;
    likedStories: Array<string>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    funny = "funny",
    other = "other",
    love = "love",
    random = "random",
    confession = "confession"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(storyId: string, content: string, timestamp: bigint, isAnonymous: boolean): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDraft(title: string, content: string, category: Category, location: Location | null, isAnonymous: boolean, image: ExternalBlob | null): Promise<string>;
    createStory(title: string, content: string, category: Category, location: Location, timestamp: bigint, isAnonymous: boolean, image: ExternalBlob | null): Promise<string>;
    deleteDraft(draftId: string): Promise<void>;
    getAllStories(): Promise<Array<Story>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(storyId: string): Promise<Array<Comment>>;
    getDraft(draftId: string): Promise<StoryDraft | null>;
    getLikedStoriesByUser(user: Principal): Promise<Array<StoryView>>;
    getPinnedStoriesByUser(user: Principal): Promise<Array<StoryView>>;
    getReports(): Promise<Array<Report>>;
    getStoriesByCategory(category: Category, sortOption: SortOption): Promise<Array<Story>>;
    getStoriesByUser(author: Principal): Promise<Array<StoryView>>;
    getStoryById(id: string): Promise<Story>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasSeenIntro(): Promise<boolean>;
    incrementStoryViewCount(id: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    likeStory(storyId: string): Promise<void>;
    listDrafts(): Promise<Array<StoryDraft>>;
    markIntroSeen(): Promise<void>;
    pinStory(storyId: string): Promise<void>;
    publishDraft(draftId: string): Promise<string>;
    removeReport(reportId: bigint): Promise<void>;
    removeStory(id: string): Promise<void>;
    reportStory(storyId: string, reason: string, timestamp: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchStories(params: SearchParams): Promise<Array<Story>>;
    unlikeStory(storyId: string): Promise<void>;
    unpinStory(storyId: string): Promise<void>;
    updateDraft(draftId: string, title: string, content: string, category: Category, location: Location | null, isAnonymous: boolean, image: ExternalBlob | null): Promise<void>;
}
import type { Category as _Category, ExternalBlob as _ExternalBlob, Location as _Location, SearchParams as _SearchParams, SortOption as _SortOption, Story as _Story, StoryDraft as _StoryDraft, StoryView as _StoryView, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDraft(arg0: string, arg1: string, arg2: Category, arg3: Location | null, arg4: boolean, arg5: ExternalBlob | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDraft(arg0, arg1, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDraft(arg0, arg1, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createStory(arg0: string, arg1: string, arg2: Category, arg3: Location, arg4: bigint, arg5: boolean, arg6: ExternalBlob | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(arg0, arg1, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(arg0, arg1, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteDraft(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDraft(arg0);
            return result;
        }
    }
    async getAllStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStories();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStories();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getDraft(arg0: string): Promise<StoryDraft | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraft(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraft(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikedStoriesByUser(arg0: Principal): Promise<Array<StoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikedStoriesByUser(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikedStoriesByUser(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedStoriesByUser(arg0: Principal): Promise<Array<StoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedStoriesByUser(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedStoriesByUser(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return result;
        }
    }
    async getStoriesByCategory(arg0: Category, arg1: SortOption): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoriesByCategory(to_candid_Category_n10(this._uploadFile, this._downloadFile, arg0), to_candid_SortOption_n32(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoriesByCategory(to_candid_Category_n10(this._uploadFile, this._downloadFile, arg0), to_candid_SortOption_n32(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoriesByUser(arg0: Principal): Promise<Array<StoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoriesByUser(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoriesByUser(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoryById(arg0: string): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryById(arg0);
                return from_candid_Story_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryById(arg0);
            return from_candid_Story_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasSeenIntro(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSeenIntro();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSeenIntro();
            return result;
        }
    }
    async incrementStoryViewCount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementStoryViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementStoryViewCount(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likeStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeStory(arg0);
            return result;
        }
    }
    async listDrafts(): Promise<Array<StoryDraft>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrafts();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrafts();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async markIntroSeen(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markIntroSeen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markIntroSeen();
            return result;
        }
    }
    async pinStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinStory(arg0);
            return result;
        }
    }
    async publishDraft(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.publishDraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishDraft(arg0);
            return result;
        }
    }
    async removeReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReport(arg0);
            return result;
        }
    }
    async removeStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStory(arg0);
            return result;
        }
    }
    async reportStory(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.reportStory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportStory(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchStories(arg0: SearchParams): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStories(to_candid_SearchParams_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStories(to_candid_SearchParams_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikeStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikeStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikeStory(arg0);
            return result;
        }
    }
    async unpinStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinStory(arg0);
            return result;
        }
    }
    async updateDraft(arg0: string, arg1: string, arg2: string, arg3: Category, arg4: Location | null, arg5: boolean, arg6: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDraft(arg0, arg1, arg2, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDraft(arg0, arg1, arg2, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_Category_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_StoryDraft_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryDraft): Promise<StoryDraft> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_StoryView_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryView): Promise<StoryView> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Story_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Promise<Story> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoryDraft]): Promise<StoryDraft | null> {
    return value.length === 0 ? null : await from_candid_StoryDraft_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    likeCount: bigint;
    content: string;
    isAnonymous: boolean;
    author: Principal;
    viewCount: bigint;
    timestamp: bigint;
    category: _Category;
    image: [] | [_ExternalBlob];
    location: _Location;
    pinCount: bigint;
}): Promise<{
    id: string;
    title: string;
    likeCount: bigint;
    content: string;
    isAnonymous: boolean;
    author: Principal;
    viewCount: bigint;
    timestamp: bigint;
    category: Category;
    image?: ExternalBlob;
    location: Location;
    pinCount: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        content: value.content,
        isAnonymous: value.isAnonymous,
        author: value.author,
        viewCount: value.viewCount,
        timestamp: value.timestamp,
        category: from_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        image: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image)),
        location: value.location,
        pinCount: value.pinCount
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    createdAt: bigint;
    isAnonymous: boolean;
    author: Principal;
    updatedAt: bigint;
    timestamp: bigint;
    category: _Category;
    image: [] | [_ExternalBlob];
    location: [] | [_Location];
}): Promise<{
    id: string;
    title: string;
    content: string;
    createdAt: bigint;
    isAnonymous: boolean;
    author: Principal;
    updatedAt: bigint;
    timestamp: bigint;
    category: Category;
    image?: ExternalBlob;
    location?: Location;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        isAnonymous: value.isAnonymous,
        author: value.author,
        updatedAt: value.updatedAt,
        timestamp: value.timestamp,
        category: from_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        image: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image)),
        location: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.location))
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    likeCount: bigint;
    content: string;
    isAnonymous: boolean;
    author: Principal;
    viewCount: bigint;
    viewers: Array<Principal>;
    timestamp: bigint;
    category: _Category;
    image: [] | [_ExternalBlob];
    location: _Location;
    pinCount: bigint;
}): Promise<{
    id: string;
    title: string;
    likeCount: bigint;
    content: string;
    isAnonymous: boolean;
    author: Principal;
    viewCount: bigint;
    viewers: Array<Principal>;
    timestamp: bigint;
    category: Category;
    image?: ExternalBlob;
    location: Location;
    pinCount: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        content: value.content,
        isAnonymous: value.isAnonymous,
        author: value.author,
        viewCount: value.viewCount,
        viewers: value.viewers,
        timestamp: value.timestamp,
        category: from_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        image: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.image)),
        location: value.location,
        pinCount: value.pinCount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    funny: null;
} | {
    other: null;
} | {
    love: null;
} | {
    random: null;
} | {
    confession: null;
}): Category {
    return "funny" in value ? Category.funny : "other" in value ? Category.other : "love" in value ? Category.love : "random" in value ? Category.random : "confession" in value ? Category.confession : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Promise<Array<Story>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Story_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoryView>): Promise<Array<StoryView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StoryView_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoryDraft>): Promise<Array<StoryDraft>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StoryDraft_n26(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SearchParams_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchParams): _SearchParams {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_SortOption_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption): _SortOption {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location | null): [] | [_Location] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sort: SortOption;
    keywords?: string;
    category?: Category;
    radius?: number;
    coordinates: Location;
}): {
    sort: _SortOption;
    keywords: [] | [string];
    category: [] | [_Category];
    radius: [] | [number];
    coordinates: _Location;
} {
    return {
        sort: to_candid_SortOption_n32(_uploadFile, _downloadFile, value.sort),
        keywords: value.keywords ? candid_some(value.keywords) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n10(_uploadFile, _downloadFile, value.category)) : candid_none(),
        radius: value.radius ? candid_some(value.radius) : candid_none(),
        coordinates: value.coordinates
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    funny: null;
} | {
    other: null;
} | {
    love: null;
} | {
    random: null;
} | {
    confession: null;
} {
    return value == Category.funny ? {
        funny: null
    } : value == Category.other ? {
        other: null
    } : value == Category.love ? {
        love: null
    } : value == Category.random ? {
        random: null
    } : value == Category.confession ? {
        confession: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "nearest";
    nearest: {
        location: Location;
    };
} | {
    __kind__: "newest";
    newest: null;
} | {
    __kind__: "mostPinned";
    mostPinned: null;
} | {
    __kind__: "mostLiked";
    mostLiked: null;
} | {
    __kind__: "mostViewed";
    mostViewed: null;
}): {
    nearest: {
        location: _Location;
    };
} | {
    newest: null;
} | {
    mostPinned: null;
} | {
    mostLiked: null;
} | {
    mostViewed: null;
} {
    return value.__kind__ === "nearest" ? {
        nearest: value.nearest
    } : value.__kind__ === "newest" ? {
        newest: value.newest
    } : value.__kind__ === "mostPinned" ? {
        mostPinned: value.mostPinned
    } : value.__kind__ === "mostLiked" ? {
        mostLiked: value.mostLiked
    } : value.__kind__ === "mostViewed" ? {
        mostViewed: value.mostViewed
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
